### ISSUE TITLE
can't yum install python3-pulp-ansible because it can't find usr/bin/ansible-test

### ISSUE THREAD

**Issue by jeremylenz** [theforeman/pulpcore-packaging#138] opened 2021-04-13 16:51 UTC
```
[vagrant@centos7-katello-devel katello]$ sudo yum install python3-pulp-ansible
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.siena.edu
 * centos-ansible-29: centos.mirror.constant.com
 * centos-sclo-rh: mirror.ash.fastserv.com
 * epel: mirror.seas.harvard.edu
 * extras: us.mirror.nsec.pt
 * updates: repos-va.psychz.net
Resolving Dependencies
--> Running transaction check
---> Package python3-pulp-ansible.noarch 1:0.7.1-1.el7 will be installed
--> Processing Dependency: python3-semantic-version for package: 1:python3-pulp-ansible-0.7.1-1.el7.noarch
--> Processing Dependency: python3-packaging for package: 1:python3-pulp-ansible-0.7.1-1.el7.noarch
--> Processing Dependency: python3-galaxy-importer for package: 1:python3-pulp-ansible-0.7.1-1.el7.noarch
--> Processing Dependency: python3-async-lru for package: 1:python3-pulp-ansible-0.7.1-1.el7.noarch
--> Running transaction check
---> Package python3-async-lru.noarch 0:1.0.2-1.el7 will be installed
---> Package python3-galaxy-importer.noarch 0:0.3.0-2.el7 will be installed
--> Processing Dependency: python3-markdown < 4 for package: python3-galaxy-importer-0.3.0-2.el7.noarch
--> Processing Dependency: python3-flake8 < 4 for package: python3-galaxy-importer-0.3.0-2.el7.noarch
--> Processing Dependency: python3-bleach-allowlist < 2 for package: python3-galaxy-importer-0.3.0-2.el7.noarch
--> Processing Dependency: python3-bleach < 4 for package: python3-galaxy-importer-0.3.0-2.el7.noarch
--> Processing Dependency: python3-markdown >= 3.2.1 for package: python3-galaxy-importer-0.3.0-2.el7.noarch
--> Processing Dependency: python3-flake8 >= 3.7.9 for package: python3-galaxy-importer-0.3.0-2.el7.noarch
--> Processing Dependency: python3-bleach-allowlist >= 1.0.3 for package: python3-galaxy-importer-0.3.0-2.el7.noarch
--> Processing Dependency: python3-bleach >= 3.3.0 for package: python3-galaxy-importer-0.3.0-2.el7.noarch
--> Processing Dependency: ansible for package: python3-galaxy-importer-0.3.0-2.el7.noarch
--> Processing Dependency: /usr/bin/ansible-test for package: python3-galaxy-importer-0.3.0-2.el7.noarch
---> Package python3-packaging.noarch 0:20.9-1.el7 will be installed
---> Package python3-semantic-version.noarch 0:2.8.5-1.el7 will be installed
--> Running transaction check
---> Package ansible.noarch 0:2.9.18-1.el7 will be installed
--> Processing Dependency: PyYAML for package: ansible-2.9.18-1.el7.noarch
--> Processing Dependency: python-jinja2 for package: ansible-2.9.18-1.el7.noarch
--> Processing Dependency: python-paramiko for package: ansible-2.9.18-1.el7.noarch
--> Processing Dependency: python-six for package: ansible-2.9.18-1.el7.noarch
--> Processing Dependency: python2-cryptography for package: ansible-2.9.18-1.el7.noarch
--> Processing Dependency: sshpass for package: ansible-2.9.18-1.el7.noarch
---> Package python3-bleach.noarch 0:3.3.0-1.el7 will be installed
--> Processing Dependency: python3-webencodings for package: python3-bleach-3.3.0-1.el7.noarch
---> Package python3-bleach-allowlist.noarch 0:1.0.3-1.el7 will be installed
---> Package python3-flake8.noarch 0:3.9.0-1.el7 will be installed
--> Processing Dependency: python3-pyflakes < 2.4.0 for package: python3-flake8-3.9.0-1.el7.noarch
--> Processing Dependency: python3-pycodestyle < 2.8.0 for package: python3-flake8-3.9.0-1.el7.noarch
--> Processing Dependency: python3-mccabe < 0.7.0 for package: python3-flake8-3.9.0-1.el7.noarch
--> Processing Dependency: python3-pyflakes >= 2.3.0 for package: python3-flake8-3.9.0-1.el7.noarch
--> Processing Dependency: python3-pycodestyle >= 2.7.0 for package: python3-flake8-3.9.0-1.el7.noarch
--> Processing Dependency: python3-mccabe >= 0.6.0 for package: python3-flake8-3.9.0-1.el7.noarch
---> Package python3-markdown.noarch 0:3.3.4-1.el7 will be installed
--> Running transaction check
---> Package PyYAML.x86_64 0:3.10-11.el7 will be installed
---> Package python-jinja2.noarch 0:2.7.2-4.el7 will be installed
--> Processing Dependency: python-babel >= 0.8 for package: python-jinja2-2.7.2-4.el7.noarch
--> Processing Dependency: python-markupsafe for package: python-jinja2-2.7.2-4.el7.noarch
---> Package python-paramiko.noarch 0:2.1.1-9.el7 will be installed
--> Processing Dependency: python2-pyasn1 for package: python-paramiko-2.1.1-9.el7.noarch
---> Package python-six.noarch 0:1.9.0-2.el7 will be installed
---> Package python2-cryptography.x86_64 0:1.7.2-2.el7 will be installed
--> Processing Dependency: python-idna >= 2.0 for package: python2-cryptography-1.7.2-2.el7.x86_64
--> Processing Dependency: python-cffi >= 1.4.1 for package: python2-cryptography-1.7.2-2.el7.x86_64
--> Processing Dependency: python-enum34 for package: python2-cryptography-1.7.2-2.el7.x86_64
---> Package python3-mccabe.noarch 0:0.6.1-1.el7 will be installed
---> Package python3-pycodestyle.noarch 0:2.7.0-1.el7 will be installed
---> Package python3-pyflakes.noarch 0:2.3.1-1.el7 will be installed
---> Package python3-webencodings.noarch 0:0.5.1-1.el7 will be installed
---> Package sshpass.x86_64 0:1.06-2.el7 will be installed
--> Running transaction check
---> Package python-babel.noarch 0:0.9.6-8.el7 will be installed
---> Package python-cffi.x86_64 0:1.6.0-5.el7 will be installed
--> Processing Dependency: python-pycparser for package: python-cffi-1.6.0-5.el7.x86_64
---> Package python-enum34.noarch 0:1.0.4-1.el7 will be installed
---> Package python-idna.noarch 0:2.4-1.el7 will be installed
---> Package python-markupsafe.x86_64 0:0.11-10.el7 will be installed
---> Package python2-pyasn1.noarch 0:0.1.9-7.el7 will be installed
--> Running transaction check
---> Package python-pycparser.noarch 0:2.14-1.el7 will be installed
--> Processing Dependency: python-ply for package: python-pycparser-2.14-1.el7.noarch
--> Running transaction check
---> Package python-ply.noarch 0:3.4-11.el7 will be installed
--> Processing Dependency: /usr/bin/ansible-test for package: python3-galaxy-importer-0.3.0-2.el7.noarch
--> Finished Dependency Resolution
 
Dependencies Resolved
 
==============================================================================================================================================================================================
 Package                                               Arch                                Version                                       Repository                                      Size
==============================================================================================================================================================================================
Installing:
 python3-pulp-ansible                                  noarch                              1:0.7.1-1.el7                                 pulpcore-3.11                                  192 k
Installing for dependencies:
 PyYAML                                                x86_64                              3.10-11.el7                                   base                                           153 k
 ansible                                               noarch                              2.9.18-1.el7                                  centos-ansible-29                               17 M
 python-babel                                          noarch                              0.9.6-8.el7                                   base                                           1.4 M
 python-cffi                                           x86_64                              1.6.0-5.el7                                   base                                           218 k
 python-enum34                                         noarch                              1.0.4-1.el7                                   base                                            52 k
 python-idna                                           noarch                              2.4-1.el7                                     base                                            94 k
 python-jinja2                                         noarch                              2.7.2-4.el7                                   base                                           519 k
 python-markupsafe                                     x86_64                              0.11-10.el7                                   base                                            25 k
 python-paramiko                                       noarch                              2.1.1-9.el7                                   base                                           269 k
 python-ply                                            noarch                              3.4-11.el7                                    base                                           123 k
 python-pycparser                                      noarch                              2.14-1.el7                                    base                                           104 k
 python-six                                            noarch                              1.9.0-2.el7                                   base                                            29 k
 python2-cryptography                                  x86_64                              1.7.2-2.el7                                   base                                           502 k
 python2-pyasn1                                        noarch                              0.1.9-7.el7                                   base                                           100 k
 python3-async-lru                                     noarch                              1.0.2-1.el7                                   pulpcore-3.11                                   12 k
 python3-bleach                                        noarch                              3.3.0-1.el7                                   pulpcore-3.11                                  251 k
 python3-bleach-allowlist                              noarch                              1.0.3-1.el7                                   pulpcore-3.11                                   19 k
 python3-flake8                                        noarch                              3.9.0-1.el7                                   pulpcore-3.11                                  123 k
 python3-galaxy-importer                               noarch                              0.3.0-2.el7                                   pulpcore-3.11                                   59 k
 python3-markdown                                      noarch                              3.3.4-1.el7                                   pulpcore-3.11                                  148 k
 python3-mccabe                                        noarch                              0.6.1-1.el7                                   pulpcore-3.11                                   16 k
 python3-packaging                                     noarch                              20.9-1.el7                                    pulpcore-3.11                                   65 k
 python3-pycodestyle                                   noarch                              2.7.0-1.el7                                   pulpcore-3.11                                   67 k
 python3-pyflakes                                      noarch                              2.3.1-1.el7                                   pulpcore-3.11                                  138 k
 python3-semantic-version                              noarch                              2.8.5-1.el7                                   pulpcore-3.11                                   33 k
 python3-webencodings                                  noarch                              0.5.1-1.el7                                   pulpcore-3.11                                   21 k
 sshpass                                               x86_64                              1.06-2.el7                                    extras                                          21 k
 
Transaction Summary
==============================================================================================================================================================================================
Install  1 Package (+27 Dependent packages)
 
Total download size: 22 M
Installed size: 125 M
Is this ok [y/d/N]: y
Downloading packages:
(1/28): PyYAML-3.10-11.el7.x86_64.rpm                                                                                                                                  | 153 kB  00:00:00    
(2/28): python-cffi-1.6.0-5.el7.x86_64.rpm                                                                                                                             | 218 kB  00:00:00    
(3/28): python-babel-0.9.6-8.el7.noarch.rpm                                                                                                                            | 1.4 MB  00:00:00    
(4/28): python-enum34-1.0.4-1.el7.noarch.rpm                                                                                                                           |  52 kB  00:00:00    
(5/28): python-idna-2.4-1.el7.noarch.rpm                                                                                                                               |  94 kB  00:00:00    
(6/28): python-markupsafe-0.11-10.el7.x86_64.rpm                                                                                                                       |  25 kB  00:00:00    
(7/28): python-jinja2-2.7.2-4.el7.noarch.rpm                                                                                                                           | 519 kB  00:00:00    
(8/28): python-paramiko-2.1.1-9.el7.noarch.rpm                                                                                                                         | 269 kB  00:00:00    
(9/28): python-pycparser-2.14-1.el7.noarch.rpm                                                                                                                         | 104 kB  00:00:00    
(10/28): python-six-1.9.0-2.el7.noarch.rpm                                                                                                                             |  29 kB  00:00:00    
(11/28): python2-cryptography-1.7.2-2.el7.x86_64.rpm                                                                                                                   | 502 kB  00:00:00    
(12/28): python2-pyasn1-0.1.9-7.el7.noarch.rpm                                                                                                                         | 100 kB  00:00:00    
(13/28): python-ply-3.4-11.el7.noarch.rpm                                                                                                                              | 123 kB  00:00:00    
(14/28): python3-async-lru-1.0.2-1.el7.noarch.rpm                                                                                                                      |  12 kB  00:00:00    
(15/28): python3-bleach-allowlist-1.0.3-1.el7.noarch.rpm                                                                                                               |  19 kB  00:00:00    
(16/28): python3-flake8-3.9.0-1.el7.noarch.rpm                                                                                                                         | 123 kB  00:00:00    
(17/28): python3-bleach-3.3.0-1.el7.noarch.rpm                                                                                                                         | 251 kB  00:00:00    
(18/28): python3-galaxy-importer-0.3.0-2.el7.noarch.rpm                                                                                                                |  59 kB  00:00:00    
(19/28): python3-mccabe-0.6.1-1.el7.noarch.rpm                                                                                                                         |  16 kB  00:00:00    
(20/28): python3-markdown-3.3.4-1.el7.noarch.rpm                                                                                                                       | 148 kB  00:00:00    
(21/28): python3-packaging-20.9-1.el7.noarch.rpm                                                                                                                       |  65 kB  00:00:00    
(22/28): python3-pycodestyle-2.7.0-1.el7.noarch.rpm                                                                                                                    |  67 kB  00:00:00    
(23/28): python3-pyflakes-2.3.1-1.el7.noarch.rpm                                                                                                                       | 138 kB  00:00:00    
(24/28): python3-pulp-ansible-0.7.1-1.el7.noarch.rpm                                                                                                                   | 192 kB  00:00:00    
(25/28): python3-semantic-version-2.8.5-1.el7.noarch.rpm                                                                                                               |  33 kB  00:00:00    
(26/28): python3-webencodings-0.5.1-1.el7.noarch.rpm                                                                                                                   |  21 kB  00:00:00    
(27/28): sshpass-1.06-2.el7.x86_64.rpm                                                                                                                                 |  21 kB  00:00:00    
warning: /var/cache/yum/x86_64/7/centos-ansible-29/packages/ansible-2.9.18-1.el7.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID 6e8b7e8a: NOKEY=====-     ] 4.5 MB/s |  20 MB  00:00:00 ETA
Public key for ansible-2.9.18-1.el7.noarch.rpm is not installed
(28/28): ansible-2.9.18-1.el7.noarch.rpm                                                                                                                               |  17 MB  00:00:02    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                         7.1 MB/s |  22 MB  00:00:03    
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-ConfigManagement
Importing GPG key 0x6E8B7E8A:
 Userid     : "CentOS Config Management SIG (https://wiki.centos.org/SpecialInterestGroup/ConfigManagementSIG) <security@centos.org>"
 Fingerprint: c75a fb57 d5c0 f238 cb15 bec8 1ae1 10fa 6e8b 7e8a
 Package    : centos-release-configmanagement-1-1.el7.centos.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-ConfigManagement
Is this ok [y/N]: y
Running transaction check
ERROR with transaction check vs depsolve:
/usr/bin/ansible-test is needed by python3-galaxy-importer-0.3.0-2.el7.noarch
 You could try running: rpm -Va --nofiles --nodigest
Your transaction was saved, rerun it with:
 yum load-transaction /tmp/yum_save_tx.2021-04-13.16-38.D1LCSL.yumtx
```

**Comment by evgeni** [comment] 2021-04-14 14:59
Not sure what's happening here. In all my tests `yum install /usr/bin/ansible-test` does the right think. Both with EPEL and the Cfg-SIG repos.

Is that reproducible and if it is, can I get access to the system it happens on?

**Comment by jeremylenz** [comment] 2021-04-14 15:09
@evgeni It was on my `centos7-katello-devel` when I was trying to get ansible set up to test https://github.com/Katello/katello/pull/9243.  Not sure if I could reproduce it.

We thought `yum install python3-pulp-ansible` should take care of its own dependencies, without erroring and without needing to explicitly install `ansible-test`.  But I am not well-versed in this area. :confused:

**Comment by jeremylenz** [comment] 2021-04-14 15:17
cc @jlsherrill @sjha4 @parthaa in case y'all want to add anything :)

**Comment by evgeni** [comment] 2021-04-14 15:17
Yeah, it should, and does in our pipelines. So not sure what's different for you.

**Comment by jeremylenz** [comment] 2021-04-14 16:17
I just tried and it seems I was also able to reproduce this on my `centos7-katello-devel-stable` just now.

**Comment by evgeni** [comment] 2021-04-19 11:42
Interesting, I can repro on you devel stable box. Installing ansible first seems to make yum happy. But why…

**Comment by evgeni** [comment] 2021-04-19 11:51
Okay, that's a "cool" bug…

You have both EPEL and the CentOS config sig repos enabled, so you could get ansible from either. (That's totally fine, in theory).
Now Ansible is packaged differently in those. In EPEL everything is in the `ansible` package, while config sig has a dedicated `ansible-test` package. When we now ask yum to install `python3-pulp-ansible`, it finds a dependency on `python3-galaxy-importer` which in turn has a dependency on `/usr/bin/ansible-test` (I originally added it as a file dependency to allow users of both kinds of Ansible packages to use it). Now it goes and looks that `EPEL:ansible` provides `/usr/bin/ansible-test` and adds `ansible` to the list of packages to install. But when it comes to actually installing things, it takes it from the config sig repo (they happen to have the same version). But that doesn't include `/usr/bin/ansible-test` and your transaction fails.

Workaround: `yum install --disablerepo=epel python3-pulp-ansible`

**Comment by jlsherrill** [comment] 2021-04-22 15:22
@evgeni i think due to this: https://github.com/theforeman/forklift/commit/e8825592a221ce6942c51354f99ca6b1a9a648a4

this will cause breakages if we try to install python3-pulp-ansible on an el7 pipeline.  We could change that to only configure it on el8?

**Comment by ehelms** [comment] 2021-04-22 15:23
Seems our test infrastructure hits this because of: https://github.com/theforeman/forklift/commit/e8825592a221ce6942c51354f99ca6b1a9a648a4 (thanks for the reminder @jlsherrill )

I think this issue currently will block/break enabling Ansible content by the Katello team.

 * Should we limit our setup to only enable the SIG repo on EL8? 
 * Should we add the workaround to our scripts and document it for users? yum install --disablerepo=epel python3-pulp-ansible

Feels kinda ugly for a default install to have to have this work around.

**Comment by evgeni** [comment] 2021-04-22 15:31
I'd limit that to EL8 then, as we do require EPEL on 7 anyways and that has everything needed.

Stupid yum tho...

**Comment by evgeni** [comment] 2021-04-22 15:32
Oh, and we don't document that people need the SIG repo when they want Ansible, so default user installs won't have it.

**Comment by jlsherrill** [comment] 2021-04-22 15:33
Should we make centos-release-ansible-29 a dependency of katello-repos for el8?  or what would be the best way to solve it?

I guess that wouldn't work for rhel installs...

**Comment by ehelms** [comment] 2021-04-22 15:45
> Should we make centos-release-ansible-29 a dependency of katello-repos for el8? or what would be the best way to solve it?
> 
> I guess that wouldn't work for rhel installs...

Yea, my gut says just include it in the installation instructions like we do with `centos-release-scl-rh`.  We also add it to puppet-foreman_proxy_content similar to https://github.com/theforeman/puppet-foreman/blob/2a9f9ed482c299749b467a92f248407c3010c9e0/manifests/repo.pp#L42

**Comment by jlsherrill** [comment] 2021-04-22 15:47
i like the docs idea, i can work on that

**Comment by evgeni** [comment] 2021-04-22 15:56
Yeah, docs it. Otherwise it won't work on RHEL or for people using local mirrors.

**Comment by jlsherrill** [comment] 2021-04-22 16:54
opened docs pr: https://github.com/theforeman/foreman-documentation/pull/509

**Comment by evgeni** [comment] 2021-04-22 17:26
Given it's documented, shall we close here?

**Comment by jlsherrill** [comment] 2021-04-22 18:14
I think that makes sense unless someone can think of a rpm spec change that would cause it to do the right thing (i can't)

**Comment by evgeni** [comment] 2021-04-23 06:26
No, not even with rich deps in EL8. If we say `Requires: (ansible-test or /usr/bin/ansible-test)` it might still pick ansible-test from SIG and ansible from EPEL and then still fail.

And that obviously doesn't even work on EL7.

**Comment by evgeni** [comment] 2021-04-23 07:05
I have opened https://bugzilla.redhat.com/show_bug.cgi?id=1952790 as I ultimately think this should be fixed by aligning EPEL to the SIG packages. (or vice versa, I don't care).

**Closed as completed by evgeni** 2021-04-23 07:05 UTC
